### ISSUE TITLE
Better integration

### ISSUE THREAD

**Issue by Quramy** [Quramy/ng-tsserver#1]
Now I rewrite `tsserver.js` to override `ts.createLanguageFunction` . Is there a better way to integrate tsserver and angular's language-service ?

**Comment by angelozerr** [comment]
@Quramy please see https://github.com/angelozerr/tsserver-plugins I have used your idea to override createLanguageService (many thank's for this great idea!)

The advantage of tsserver-plugin are :

 * follow the same idea than the future of TypeScript (declared plugins in your tsconfig.json)
 * not rewrite tsserver.js, but concat at runtime teh before.js and the tsserver.js

Thanks again for your great idea!

**Comment by Quramy** [comment]
@angelozerr Thanks. 
I'm looking forward to the PR https://github.com/Microsoft/TypeScript/pull/12231 😄
